name: Matrix Demo           # Run same job with different configurations (runners, node versions, etc)
on:
  push:
jobs:
  build:
    continue-on-error: true       # Makes sure that the job passes even if some combination fails
    strategy:
      matrix:
        node-version: [12, 16, 18, 20]
        operating-system: [ubuntu-latest, windows-latest]     # Variables named by user
        include:                        # Allows us to add standalone/specific combination
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:                        # Allows us to remove standalone/specific combination
          - node-version: 12
            operating-system: windows-latest  
          - node-version: 12
            operating-system: ubuntu-latest         
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
        