name: Reusable Deploy
on: workflow_call         # Here we can make it callable from another workflow
                          # workflow_dispatch : Manually running a workflow
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: echo " Deploying & Uploading"